### ISSUE TITLE
igawa asagi

### ISSUE THREAD

**Issue by AH800** [sst311212/ActionTaimaninOneKeyNude#12]
broken full nude skin

**Comment by sst311212** [comment]
I will remove asagi full nude mod temporally, wait until moderchan release update. dcb886156284c39cc97fd71d2b66f3addee04368

**Comment by Thandum** [comment]
In the meantime, can you at least put the Igawa asagi orig nude model?

**Comment by sst311212** [comment]
08d75ff4e3c6eb5cd298ea4cae77c33ab4f52ad8 fixed.
