### ISSUE TITLE
Murasaki / Shiranui Gloss

### ISSUE THREAD

**Issue by zerg2525** [sst311212/ActionTaimaninOneKeyNude#19]
![1](https://user-images.githubusercontent.com/115714401/236181322-5b24e125-cce5-4b29-9f69-4ae9f710a2cf.jpg)

hello
First of all, thank you for continuing to update the data.

It's none other than Murasaki/Shiranui's body and face colors don't seem to match, so I'm writing this to ask a question.

**Comment by sst311212** [comment]
Okay, I know what's the problem.
Mobile version use ETC2_RGB4 texture format, it's different with PC version.
I need maintenance 2 projects at the same time, such a pain....

**Comment by sst311212** [comment]
Fixed: db83fab5300b65d826b875a942207f0ed0ead878

![sshot-0002](https://user-images.githubusercontent.com/8367844/236420099-2e63a764-a93a-405c-9e38-6049f64503e2.png)
![sshot-0003](https://user-images.githubusercontent.com/8367844/236420330-4ed6566b-cc19-4e88-b8f7-783d0159d3ed.png)

**Comment by zerg2525** [comment]
Thank you very much T^T
Thank you for the wonderful gift
