### ISSUE TITLE
Updated December 6, 23

### ISSUE THREAD

**Issue by zerg2525** [sst311212/ActionTaimaninOneKeyNude#20]
I heard it doesn't seem to be working normally since December 6, 23rd update. Is it because the data has changed as it has been updated? T^T

**Comment by sst311212** [comment]
It should be fixed after 3686fbd.

**Comment by zerg2525** [comment]
Thank you very much 0ㅇ0 b

**Comment by zerg2525** [comment]
Thank you very much 0ㅇ0 b
