### ISSUE TITLE
Is it me or the mod not working anymore 

### ISSUE THREAD

**Issue by Chymtoi** [sst311212/ActionTaimaninOneKeyNude#23]
I got the two patches file to the obb file on my phone but nothing happened

**Comment by Chymtoi** [comment]
It tells me I'm missing the ./mod_char file

**Comment by sst311212** [comment]
It does work on my phone.
I download the latest version of game from Google Play.
Batch script should pull out `patch.616.com.GREMORYGames.ActionTaimanin.obb` file from mobile.
You can use 7-Zip to open `obb` file and check if `model_char` is exist in archive?

**Comment by Chymtoi** [comment]
There is but idk how the mod didn't works
![Uploading 17241705859438295660673731380997.jpg…]()

**Comment by Chymtoi** [comment]
I packed the new onb file and move it to my mobile but the game doesnt load

**Comment by zerg2525** [comment]
It works fine for me too. Thanks for the updates as always.

**Comment by sst311212** [comment]
Maybe [ObbAssit.exe](https://github.com/sst311212/ActionTaimaninOneKeyNude/blob/main/ObbAssit.exe) didn't work on your computer, anti-virus may prevent this program running or your system didn't installed [.NET Framework 4.8](https://dotnet.microsoft.com/zh-tw/download/dotnet-framework/net48).
