### ISSUE TITLE
Inquiry regarding merging 3rdParty folders

### ISSUE THREAD

**Issue by zerg2525** [sst311212/ActionTaimaninOneKeyNude#24]
Thank you for always updating the mod 

I have no place to ask questions, so I ask for your understanding as I am posting on the issue board

I would like to question if it is possible to add the files of Emily23+Kirara8+Oboro6 to the 3rdParty folder as Mod.exe
- The PC version can be installed by setting the file as the installation path, but I don't know how to do it for mobile phones   T^T

**Comment by sst311212** [comment]
This 3rdParty Mod is buggy now (Mesh issue), and it only support PC version.
I don't recommend install this Mod.

**Comment by zerg2525** [comment]
Yes, thank you for your answer
