### ISSUE TITLE
Inquire about applying the mode

### ISSUE THREAD

**Issue by zerg2525** [sst311212/ActionTaimaninOneKeyNude#25]
![11](https://github.com/user-attachments/assets/82d59b5b-5c8c-45ee-90c2-42c79f3ec5be)

Thank you for always updating the mod.

After this update, the 3rdParty file changed, so I tried to download and install the currently uploaded Ver, but I confirmed that the mod was not applied after the image above appeared.
- It was applied normally on the PC, but it was not applied on the Android phone.
Do you know what the cause is? ㅠ

**Comment by sst311212** [comment]
They start using split apk, and we cannot patch obb files likes before.
Because apk has signing check, so is not possible to repack it.

**Comment by zerg2525** [comment]
oh my god....
